MY_ZSH=${HOME}/.zsh

source ${MY_ZSH}/path.zsh
source ${MY_ZSH}/exports.zsh

if [ "$(uname -s)" = "Darwin" ]; then
  # MacOS path setup
  COREUTILS_PATH="$(brew --prefix coreutils)/libexec/gnubin"
  prepend_path ${COREUTILS_PATH}
  prepend_manpath ${COREUTILS_PATH}
fi
