# Source global definitions
[ -f /etc/zshrc ] && source /etc/zshrc

export ZSH="${HOME}/.oh-my-zsh"
MY_ZSH=${DOTFILES}/zsh

source ${MY_ZSH}/oh-my-zsh-specific.sh
source ${MY_ZSH}/prompt.sh
source ${ZSH}/oh-my-zsh.sh

# my options
source ${MY_ZSH}/aliases.sh
source ${MY_ZSH}/completion.sh
source ${MY_ZSH}/history.sh
source ${MY_ZSH}/options.sh

# any local settings ?
[ -f ~/.zshrc.local ] && source ~/.zshrc.local

# source fuzzy finder
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export PATH="$(cleanup_path $PATH)"
export MANPATH="$(cleanup_path $MANPATH)"
