# Source global definitions
[ -f /etc/zshrc ] && source /etc/zshrc

export ZSH="${HOME}/.oh-my-zsh"
MY_ZSH=${HOME}/.zsh

source ${MY_ZSH}/oh-my-zsh-specific.zsh
source ${MY_ZSH}/prompt.zsh
source ${ZSH}/oh-my-zsh.sh

# my options
source ${MY_ZSH}/aliases.zsh
source ${MY_ZSH}/history.zsh
source ${MY_ZSH}/options.zsh

# any local settings ?
[ -f ~/.zshrc.local ] && source ~/.zshrc.local

# source fuzzy finder
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
