# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Source global definitions
[ -f /etc/zshrc ] && source /etc/zshrc

export ZSH="${HOME}/.oh-my-zsh"
MY_ZSH=${DOTFILES}/zsh

source ${MY_ZSH}/oh-my-zsh-specific.sh
source ${MY_ZSH}/prompt.sh
source ${ZSH}/oh-my-zsh.sh

# my options
source ${MY_ZSH}/aliases.sh
source ${MY_ZSH}/completion.sh
source ${MY_ZSH}/history.sh
source ${MY_ZSH}/options.sh

# any local settings ?
[ -f ~/.zshrc.local ] && source ~/.zshrc.local

# source fuzzy finder
source $DOTFILES/shell/fzf.sh

export PATH="$(cleanup_path $PATH)"
export MANPATH="$(cleanup_path $MANPATH)"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[ -f ~/.p10k.zsh ] && source ~/.p10k.zsh
