[ -f /etc/bashrc ] && source /etc/bashrc

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

MY_BASH="${HOME}/.bash"

source "${MY_BASH}/path.sh"
source "${MY_BASH}/exports.sh"
source "${MY_BASH}/aliases.sh"
source "${MY_BASH}/prompt.sh"

eval $(dircolors ${MY_BASH}/dircolors)

# default umask
umask 022

# fail if any command in pipe fails, not only last one
set -o pipefail
# vi key bindings
set -o vi

# history
shopt -s histappend
HISTCONTROL=ignoreboth
HISTSIZE=1000000
HISTFILESIZE=1000000

shopt -s checkwinsize

# If set, the pattern "**" used in a pathname expansion context will
# match all files and zero or more directories and subdirectories.
#shopt -s globstar

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# Add tab completion for SSH hostnames based on ~/.ssh/config, ignoring wildcards
[ -e "$HOME/.ssh/config" ] && complete -o "default" -o "nospace" -W "$(grep "^Host" ~/.ssh/config | grep -v "[?*]" | cut -d " " -f2- | tr ' ' '\n')" scp sftp ssh;


if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

[ -f ~/.fzf.bash ] && source ~/.fzf.bash
